name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        configuration: [Debug, Release]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 9 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution (${{ matrix.configuration }})
      run: dotnet build --no-restore --configuration ${{ matrix.configuration }} --verbosity minimal

    - name: Test solution (${{ matrix.configuration }})
      run: dotnet test --configuration ${{ matrix.configuration }} --no-build --verbosity normal


  LINT: 
    runs-on: ubuntu-latest
    needs: build-and-test
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 9 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Lint with dotnet-format
      run: dotnet format --verify-no-changes --verbosity normal

